# [target.xtensa-esp32s3-none-elf]
[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor --log-format defmt"
# runner = "espflash flash --monitor --log-format defmt"
[target.'cfg(target_arch = "riscv32")']
rustflags = ["-C", "force-frame-pointers"]

[env]
ESP_LOG = "INFO"

[build]
rustflags = ["-C", "link-arg=-nostartfiles"]

# target = "xtensa-esp32s3-none-elf"
target = "riscv32imc-unknown-none-elf"
[unstable]
build-std = ["alloc", "core"]
