# [toolchain]
# channel = "esp"


[toolchain]
channel = "nightly"
components = ["rust-src"]
targets = ["riscv32imac-unknown-none-elf"]


# Chip	Datasheet	Technical Reference Manual	Target
# ESP32	ESP32	ESP32	xtensa-esp32-none-elf
# ESP32-C2	ESP32-C2	ESP32-C2	riscv32imc-unknown-none-elf
# ESP32-C3	ESP32-C3	ESP32-C3	riscv32imc-unknown-none-elf
# ESP32-C6	ESP32-C6	ESP32-C6	riscv32imac-unknown-none-elf
# ESP32-H2	ESP32-H2	ESP32-H2	riscv32imac-unknown-none-elf
# ESP32-S2	ESP32-S2	ESP32-S2	xtensa-esp32s2-none-elf
# ESP32-S3	ESP32-S3	ESP32-S3	xtensa-esp32s3-none-elf
