[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
# runner = "probe-rs run --chip=esp32c6 --preverify --always-print-stacktrace --no-location --catch-hardfault"


[env]
ESP_LOG = "INFO"

[build]
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "force-frame-pointers"]
target = "riscv32imac-unknown-none-elf"
[unstable]
build-std = ["alloc", "core"]
